#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
base=`echo $DIR | sed 's|\(.*\)/.*|\1|'`

echo "Enter the current path of the image you want to use:"
read original

filename=$(basename -- "$original" | sed -e 's/[^A-Za-z0-9._-]/_/g')
extension="${filename##*.}"
filename="${filename%.*}"
timestamp="$(date +%s)"
newname="$filename-$timestamp.$extension"
syntax="/images/hugo/$newname"

cp $original $base/static/images/hugo/$newname

echo "Uploaded image path:
$syntax"
