#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
base=`echo $DIR | sed 's|\(.*\)/.*|\1|'`

filename=$(basename -- "$1" | sed -e 's/[^A-Za-z0-9._-]/_/g')
extension="${filename##*.}"
filename="${filename%.*}"
timestamp="$(date +%s)"
newname="$filename-$timestamp.$extension"
syntax="/images/hugo/$newname"

if [[ "$OSTYPE" == "linux-gnu"* ]]
then
  echo -n "$syntax" | xclip -sel clip
elif [[ "$OSTYPE" == "darwin"* ]]
then
  echo -n "$syntax" | pbcopy
fi

cp $1 $base/static/images/hugo/$newname

echo "Relative link:
$syntax
Copied to your clipboard"
